run:
	python3 manage.py runserver

runs:
	./manage.py runserver 0.0.0.0:8000

migrate:
	./manage.py makemigrations
	./manage.py migrate

statics:
	./manage.py collectstatic

user:
	./manage.py createsuperuser
